### ISSUE TITLE
Authorized clients timing out

### ISSUE THREAD

**Issue by AldsteCarter** [adryd325/sneaky#9] opened 2023-07-30 14:05 UTC
It appears that with the default configuration settings, when an authorized client connects to the server, they are subsequently timed out. The clients didn't have issues beforehand.

I am running this server with itzg's docker image with the autopause feature enabled.

There isn't any other information provided in legs, other than a connect, then timeout. Is nhis perhaps due to the rate limiting?

**Comment by adryd325** [comment] 2023-07-30 19:35
Do the time outs occur while connecting or after they have joined?

If they occur while connecting, try increasing new-connection-rate-limit to 10 or 15.

**Comment by AldsteCarter** [comment] 2023-07-31 04:40
The disconnects happen after joining the server from 10s to a few minutes after authenticating. Here is some log.

`[01:39:27] [User Authenticator #88/INFO]: UUID of player User1 is ************
[01:39:28] [Server thread/INFO]: User1[/************] logged in with entity id 217134 at (84.69999998807907, 214.0625, 209.87946970772677)
[01:39:28] [Server thread/INFO]: User1 joined the game
[01:39:29] [User Authenticator #89/INFO]: UUID of player User2 is ************
[01:39:30] [Server thread/INFO]: User2[/************] logged in with entity id 217652 at (417.3672153148316, 94.92159999847412, -274.97276513011354)
[01:39:30] [Server thread/INFO]: User2 joined the game
[01:41:30] [Server thread/INFO]: [Rcon: Saved the game]
[2023-07-27T01:41:30-06:00] [Autopause] Pausing Java process
[01:42:03] [Server thread/INFO]: User1 lost connection: Timed out
[01:42:03] [Server thread/INFO]: User1 left the game
[01:42:03] [Server thread/INFO]: User2 lost connection: Timed out
[01:42:03] [Server thread/INFO]: User2 left the game`

**Comment by adryd325** [comment] 2023-07-31 05:53
Can you test without the mod installed for an extended period of time and see if it still occurs

**Comment by adryd325** [comment] 2023-07-31 20:06
Looking closer this might be a problem with Autopause pausing the game while players are still online, not with Sneaky. Can you create an issue with the Autopause mod you're using?

For the time being I'll close this cause I can't reproduce and it really shouldnt be an issue caused by sneaky since we only close connections at the very start of the connection; and we close the TCP connection rather than letting it hang.

**Closed as completed by adryd325** 2023-07-31 20:06 UTC

**Comment by AldsteCarter** [comment] 2023-08-01 05:51
After removing the mod, clients are not timed out.

**Comment by AldsteCarter** [comment] 2023-08-01 05:55
I will do so. It is odd, however, that after removing the mod, timeouts do not occur. Maybe, this is something more suited for the developers over there.

**Comment by adryd325** [comment] 2023-08-01 05:59
It may be worth opening an issue with them and link the issue here and we'll try to figure out what's going on

**Comment by itzg** [comment] 2023-08-01 16:15
> Looking closer this might be a problem with Autopause pausing the game while players are still online, not with Sneaky

@adryd325 How did you determine that? If Minecraft server logs are reporting the activity then that has nothing to do with autopause nor being a containerized instance of the Minecraft server. 

The OP has clarified that no problem occurs with SneakyServer mod removed but occurs when installed.

**Comment by adryd325** [comment] 2023-08-01 16:47
@itzg I determined that autopause is the issue cause theres no leave messages before AutoPause. If the process is being paused, of course clients are going to be timed out cause the java process isn't able to respond to things while paused.

I also don't touch the tcp connection at all after it's created. I close connections properly before they even reach Minecraft's network handlers if they've hit ratelimits for opening new connections.

**Comment by xyzeva** [comment] 2023-08-01 16:54
I cant reproduce this issue,

As seen in the source code, Sneaky only touches the `initChannel` method of the TCP connection and some `INVOKE` mixins for legacy ping.  Maybe the OP has a different configuration then the default.

**Comment by itzg** [comment] 2023-08-01 17:02
Thanks for the clarifications. I'll continue the convo over on the follow up issue.
